config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  get 'books'=>'books#index'
  post 'books'=> 'books#create'
  get 'books/:id'=>'books#show',as:'book'
  get 'books/:id/edit'=> 'books#edit',as:'edit_book'
  patch 'books/:id'=>'books#update',as:'update_book'
  delete 'books/:id'=>'books#destroy',as:'destroy_book'
  root :to =>"homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @books=Book.all
    @book=Book.new(params[:id])
  end

  def show
    @book=Book.find(params[:id])
  end

  def create
    @book=Book.new(book_params)
    if @book.save
       flash[:notice] = "Book was successfully created"
       redirect_to book_path(@book)
    else
      @books=Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "Book was successfully created"
       redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def book
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<!--投稿編集フォーム-->
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local: true do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

 <p><%= f.submit 'Update Book' %></p>

<% end %>

<!--ボタン表示-->
<%= link_to "Show", book_path(@book.id) %>
<%= "|" %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<!--投稿一覧-->
<h2>Books</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to "Show",book_path(book.id) %></td>
     <td><%= link_to "Edit",edit_book_path(book) %></td>
     <td><%= link_to "Destroy",destroy_book_path(book.id),method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>

    <% end %>
  </tbody>
</table>
<!--投稿フォーム-->
<h2>New book</h2>
<!--エラー表示-->
<div class="error">
  <div class="error_message">
   <% if @book.errors.any? %>
     <%= @book.errors.count %>errors prohibited this book from being saved:
     <ul>
       <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   <% end %>
  </div>
</div>

<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <p><%= f.submit 'Create Book' %></p>
<% end %>

app/views/books/new.html.erb
<h1>suzukikazuya</h1>

app/views/books/show.html.erb
<% if  flash[:notice] %>
 <div class="flash">
   <%= flash[:notice] %>
 </div>
<% end %>

<table>
 <tbody>
  <tr>
   <th>Title:</th>
   <td><%= @book.title %></td>
  </tr>

  <tr>
   <th>Body:</th>
   <td><%= @book.body %></td>
  </tr>

</table>

<%= link_to "Edit", edit_book_path(@book.id) %>
<%= " |" %>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ!</h1>
<p><%= "Bookers では、さまざまな書籍に関するあなたの意見や"%></p>

<p><%= "印象を共有し交換することができます" %></p>

<%= link_to "start", books_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>